apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: webserver-1
    environment: test
    authorship: sunil
spec:
  containers:
  - name: c1
    image: nginx:latest
    ports:
    - containerPort: 80